RePOS/Controllers/Analytics/OrderReportController.cs
using Microsoft.AspNetCore.Mvc;
using RePOS.Models;
using RePOS.Data;
using Microsoft.EntityFrameworkCore;

namespace RePOS.Controllers.Analytics
{
    public class OrderReportController : Controller
        {
        private readonly RePosDBContext _context;
        public OrderReportController(RePosDBContext context)
        {
            _context = context;
        }
        [HttpGet, Route("Analytics/Order/Report")]
        public IActionResult Index()
        {
            var orders = _context.Orders
                .Include(o => o.PaymentMethod)
                .ToList();

             ViewBag.Orders = orders;
            return View("~/Views/Analytics/OrderReport.cshtml");
        }
    }
}

RePOS/Controllers/POS/PosController.cs
using Microsoft.AspNetCore.Mvc;
using RePOS.Data;
using RePOS.Models;
using RePOS.Dtos;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace RePOS.Controllers
{
    public class PosController : Controller
    {
        private readonly RePosDBContext _context;

        public PosController(RePosDBContext context)
        {
            _context = context;
        }

        [HttpGet, Route("Order/Create"), Authorize]
        public IActionResult Index()
        {
            ViewBag.Items = _context.Items.ToList();
            ViewBag.PaymentMethods = _context.PaymentMethods.ToList();
            return View("~/Views/POS/Create.cshtml");
        }

        [HttpPost, Route("Order/Create")]
        [ValidateAntiForgeryToken]
        public IActionResult Create(OrderCreateDto dto)
        {
            if (!ModelState.IsValid || dto.OrderItems == null || !dto.OrderItems.Any())
            {
                return RedirectToAction("Index");
            }

            var paymentMethod = _context.PaymentMethods.FirstOrDefault(pm => pm.Id == dto.PaymentMethodId);
            if (paymentMethod == null)
            {
                TempData["ErrorMessage"] = "Invalid payment method.";
                return RedirectToAction("Index");
            }

            decimal totalAmount = 0;

            var order = new Order
            {
                PaymentMethodId = dto.PaymentMethodId,
                OrderItems = new List<OrderItem>()
            };

            foreach (var itemDto in dto.OrderItems)
            {
                var item = _context.Items.FirstOrDefault(i => i.Id == itemDto.ItemId);
                if (item == null)
                    continue;

                var orderItem = new OrderItem
                {
                    ItemId = item.Id,
                    Quantity = itemDto.Quantity,
                };

                totalAmount += item.Price * itemDto.Quantity;

                order.OrderItems.Add(orderItem);
            }

            order.Total = totalAmount;

            _context.Orders.Add(order);
            _context.SaveChanges();
            TempData["Success"] = "Order created successfully.";

            return RedirectToAction("Index");
        }
    }
}

RePOS/Controllers/Setup/PaymentMethodController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RePOS.Data;
using RePOS.Models;

namespace RePOS.Controllers.Setup
{
    public class PaymentMethodController : Controller
    {
        private readonly RePosDBContext _context;
        public PaymentMethodController(RePosDBContext context)
        {
            _context = context;
        }


        [Route("PaymentMethods"), Authorize]
        public IActionResult Index()
        {
            var payment_methods = _context.PaymentMethods.ToList();
            return View("~/Views/Setup/PaymentMethod/Index.cshtml", payment_methods);
        }
        [Route("PaymentMethod/Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PaymentMethod pm)
        {
            if (ModelState.IsValid)
            {
                _context.PaymentMethods.Add(pm);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pm);

        } // Create a new category

        [Route("PaymentMethod/Edit/{id}")]
        [HttpPost]
        public IActionResult Edit(int id, PaymentMethod pm)
        {

            var paymentMethod = _context.PaymentMethods.Find(id);
            if (paymentMethod == null)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                paymentMethod.Name = pm.Name;
                _context.PaymentMethods.Update(paymentMethod);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pm);
        }

        [Route("PaymentMethod/Delete/{id}")]
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var pm = _context.PaymentMethods.Find(id);
            if (pm == null)
            {
                return RedirectToAction("Index");
            }
            _context.PaymentMethods.Remove(pm);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

RePOS/Controllers/Setup/StaffController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RePOS.Data;
using RePOS.Models;

namespace RePOS.Controllers.Setup
{
    public class StaffController : Controller
    {
        private readonly RePosDBContext _context;

        public StaffController(RePosDBContext context)
        {
            _context = context;
        }

        [Route("Staffs"), Authorize]
        public IActionResult Index()
        {
            var staffs = _context.Staffs.ToList();
            return View("~/Views/Setup/Staff/Index.cshtml", staffs);
        }

        [Route("Staff/Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                Console.WriteLine(staff);
                _context.Staffs.Add(staff);
                _context.SaveChanges();
                return RedirectToAction("Index");

            }
            return View();
        }

        [Route("Staff/Edit/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, Staff staff)
        {
            if (id != staff.Id)
            {
                return BadRequest();
            }

            var existingStaff = _context.Staffs.Find(id);
            if (existingStaff == null)
            {
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                existingStaff.FullName = staff.FullName;
                existingStaff.Email = staff.Email;
                if (!string.IsNullOrEmpty(staff.Password))
                {
                    existingStaff.Password = staff.Password; // Update password only if provided
                }
                existingStaff.IsAdmin = staff.IsAdmin;
                existingStaff.Status = staff.Status;
                _context.Staffs.Update(existingStaff);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

RePOS/Views/Shared/_Footer.cshtml
<footer class="main-footer text-center">
    <strong>RePoS</strong> | Made By <a href="#">Team KichuParina</a> with ❤️
</footer>

RePOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> @ViewData["Title"] </title>
    <meta name="description" content="RePOS - Restaurant Point of Sale System">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <!-- AdminLTE CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/css/adminlte.min.css" rel="stylesheet">
    <!-- Date Range Picker -->
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
    <!-- Chart Js -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->      
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto mb-2">
                <!-- User avatar and name -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-bs-toggle="dropdown" href="#" aria-expanded="false">
                        <div class="user-panel mr-2 d-flex">
                            <div class="image">
                                <img src="https://api.dicebear.com/9.x/bottts-neutral/png?size=64&seed=foo" class="img-circle" alt="User Image">
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-md dropdown-menu-right mt-1 p-3" style="left: inherit; right: 0px;" aria-labelledby="navbarDropdown">
                        <div class="dropdown-item d-flex p-2">
                            <img src="https://api.dicebear.com/9.x/bottts-neutral/png?size=64&seed=foo" class="img-circle" alt="User Image" width="36px" height="100%">
                            <div class="ml-2">
                                <div class="text-sm font-medium">foo</div>
                                <div class="text-xs">foo</div>
                            </div>
                        </div>
                        <div class="dropdown-divider"></div>
                        <a href="#" class="dropdown-item">
                            <i class="fas fa-user mr-2"></i> Profile
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="@Url.Action("Logout", "Auth")" class="dropdown-item">
                            <i class="fas fa-sign-out-alt mr-2"></i> Logout
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-secondary elevation-3">
            <!-- Sidebar -->
            <!-- Brand Logo -->
            <a href="#" class="brand-link text-center">
                <span class="brand-text font-weight-light">RePOS</span>
            </a>
            <div class="sidebar">
                <!-- Sidebar Menu -->
                    @Html.Partial("_Sidebar")
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h3 class="m-0">
                                <!-- Left Header content goes here -->
                                @ViewData["PageName"]
                            </h3>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <!-- Right Header content goes here -->
                            @RenderSection("HeaderRight", required: false)
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    <div class="row">
                        <!-- Content goes here -->
                            @RenderBody()
                        <!-- ./Content goes here -->
                    </div> <!-- ./row -->
                </div><!-- ./container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
        </aside>
        <!-- /.control-sidebar -->
       
        <!-- Main Footer -->
            @Html.Partial("_Footer")
        <!-- ./Main Footer -->

    </div>
    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- Bootstrap 5 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/3.2.0/js/adminlte.min.js"></script>
    <!-- Date Range Picker -->
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

    <!-- Custom JS -->
    <script>
        function handleAction(url) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    // Perform the action here, e.g., delete the item
                    axios.post(url, {
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded'
                        }
                    })
                    .then(response => {
                        Swal.fire({
                            title: 'Deleted!',
                            text: 'Your file has been deleted.',
                            icon: 'success',
                            timer: 3000, // Popup will stay for 3 seconds
                            timerProgressBar: true, // Show a progress bar
                            willClose: () => {
                                location.reload(); // Reload the page after the popup closes
                            }
                        });
                    });
                }
            });
        }
    </script>


</body>
</html>

RePOS/Views/Shared/_Sidebar.cshtml
@using System.Security.Claims

<nav class="mt-5">
    <!-- Control sidebar content goes here -->
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
            with font-awesome or any other icon font library -->
        <li class="nav-item">


            <a href="@Url.Action("Index", "Home")" class="nav-link">
                <i class="nav-icon fas fa-tachometer-alt"></i>
                <p>
                    Dashboard
                </p>
            </a>
        </li>
        <li class="nav-item">
            <a href="@Url.Action("Index", "Pos")" class="nav-link">
                <i class="nav-icon fa-solid fa-cart-shopping"></i>
                <p>
                    Point Of Sale
                </p>
            </a>
        </li>
        <li class="nav-item has-treeview mb-2">
            <a href="#" class="nav-link">
                <i class="nav-icon fa-solid fa-chart-line"></i>
                <p>
                    Analytics
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <!-- Setup Link -->
                <li class="nav-item">
                    <a href="@Url.Action("Index", "OrderReport")" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>
                            Orders Report
                        </p>
                    </a>
                </li>
            </ul>
        </li>
        @if (User.HasClaim(c => c.Type == "IsAdmin" && c.Value == "True"))
        {
            <li class="nav-item has-treeview mb-2">
                <a href="#" class="nav-link">
                    <i class="nav-icon fa-solid fa-gear"></i>
                    <p>
                        Setup
                        <i class="right fas fa-angle-left"></i>
                    </p>
                </a>
                <ul class="nav nav-treeview">
                    <!-- Setup Link -->
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Item")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>
                                Items
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "PaymentMethod")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>
                                Payment Methods
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="@Url.Action("Index", "Staff")" class="nav-link">
                            <i class="far fa-circle nav-icon"></i>
                            <p>
                                Staff
                            </p>
                        </a>
                    </li>
                </ul>
            </li>
        }
    </ul>
</nav>